# Generated by Django 5.2.6 on 2025-09-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_ngo_profile_alter_restaurant_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('pickup_time', models.TimeField()),
                ('pickup_date', models.DateField()),
                ('status', models.CharField(choices=[('Ld', 'Listed'), ('Clmd', 'Claimed'), ('Clcd', 'Collected')])),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant')),
            ],
        ),
    ]
