# Generated by Django 5.2.6 on 2025-09-26 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pickup_time',
        ),
        migrations.AddField(
            model_name='orders',
            name='pickup_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
