# Generated by Django 5.2.6 on 2025-09-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_orders_pickup_date_remove_orders_pickup_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Ld', 'Listed'), ('Clmd', 'Claimed'), ('Clcd', 'Collected')], default='Ld'),
        ),
    ]
