# Generated by Django 5.2.6 on 2025-09-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_ngo_profile_alter_restaurant_profile'),
        ('base', '0003_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='claimed_ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ngo'),
        ),
    ]
