# Generated by Django 5.2.6 on 2025-09-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='ngo/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='rest/'),
        ),
    ]
